version: '3.8'

services:
  web:
    build: ./sm_app
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - ./sm_app/:/usr/src/sm_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sm_project
      - POSTGRES_PASSWORD=sm_project
      - POSTGRES_DB=sm_project_dev

volumes:
  postgres_data:
