# Generated by Django 4.1.5 on 2023-02-14 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=200)),
                ('checklist_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_status', models.IntegerField(choices=[(1, 'Completed'), (2, 'In Review'), (3, 'Incomplete')], default=3)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_app.checklist')),
            ],
        ),
    ]
