# Generated by Django 4.1.5 on 2023-02-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_status', models.IntegerField(choices=[(1, 'Completed'), (2, 'In Review'), (3, 'Incomplete')], default=3)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_app.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_users',
            field=models.ManyToManyField(to='sm_app.user'),
        ),
    ]
